version: "3.9"

services:
  mongodb:
    image: mongo:8.0
    container_name: fluxori-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - fluxori-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluxori-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/fluxori?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - fluxori-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluxori-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fluxori-network

networks:
  fluxori-network:
    driver: bridge

volumes:
  mongodb_data:
