'use client';

/**
 * Shared types for motion and animation features
 * This module contains shared types and interfaces used by both UI and Motion modules
 * to prevent circular dependencies between them.
 */

/**
 * Connection quality levels for bandwidth-aware animations
 * - high: Fast connections (WiFi, strong 4G)
 * - medium: Average connections (3G, weak 4G)
 * - low: Slow connections (2G, weak 3G)
 * - poor: Very slow connections (2G or worse, high latency areas common in rural South Africa)
 */
export type ConnectionQuality = 'high' | 'medium' | 'low' | 'poor';

/**
 * Network condition types used in animation strategies
 */
export type NetworkCondition = 'fast' | 'medium' | 'slow' | 'poor';

/**
 * User-selectable motion preference modes
 */
export type MotionMode = 'full' | 'reduced' | 'minimal';

/**
 * Result from the connection quality detection
 */
export interface ConnectionQualityResult {
  /** Current connection quality assessment */
  quality: ConnectionQuality;
  
  /** Whether data saver mode is enabled */
  isDataSaver: boolean;
  
  /** Whether the connection is metered (pay-per-use) */
  isMetered: boolean;
  
  /** Raw downlink speed in Mbps (if available) */
  downlinkSpeed?: number;
  
  /** Raw round-trip time in ms (if available) */
  rtt?: number;
  
  /** Raw effective connection type (if available) */
  effectiveType?: string;
}

/**
 * Types of animations that can be applied to components
 */
export type AnimationMode = 'hover' | 'press' | 'focus' | 'error' | 'success' | 'loading' | 'shake' | 'appear';

/**
 * Animation strategy configuration
 */
export interface AnimationStrategyConfig {
  /** Animation type */
  animationType: AnimationMode;
  
  /** Motion mode from user preference */
  motionMode: MotionMode;
  
  /** Whether to optimize for network conditions */
  networkAware?: boolean;
  
  /** Current network condition (if known) */
  networkCondition?: NetworkCondition;
  
  /** Whether to respect reduced motion settings */
  shouldReduceMotion?: boolean;
  
  /** Custom duration multiplier (1.0 = default) */
  customDuration?: number;
}

/**
 * Animation parameters generated by the strategy
 */
export interface AnimationParams {
  /** Whether animations should run at all */
  enabled: boolean;
  
  /** Duration multiplier (1.0 = default, 0.5 = half speed) */
  durationMultiplier: number;
  
  /** Whether to use simplified easings */
  useSimpleEasings: boolean;
  
  /** Whether to reduce motion complexity */
  reduceComplexity: boolean;
  
  /** Maximum active animations */
  maxActiveAnimations: number;
  
  /** Whether to disable staggering effects */
  disableStaggering: boolean;
  
  /** Animation scale multiplier */
  scaleMultiplier: number;
}

/**
 * Type for AI confidence levels
 */
export type ConfidenceLevel = 'low' | 'medium' | 'high' | 'verifying' | 'processing';