name: ADR Visualization Update

on:
  push:
    branches: [main]
    paths:
      - "backend/src/**"
      - "backend/.dependency-cruiser.js"
  pull_request:
    paths:
      - "backend/src/**"
      - "backend/.dependency-cruiser.js"
  workflow_dispatch:

jobs:
  update-adr-visualizations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Install dependencies
        run: |
          cd scripts/adr
          npm install

      - name: Update ADR visualizations
        run: |
          cd scripts/adr
          ./update-adr-visualizations.sh --verbose

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code docs/adr/visualizations || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes if any
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "chore: update ADR visualizations"
          add: "docs/adr/visualizations"

      - name: Upload ADR visualizations as artifacts for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: adr-visualizations
          path: docs/adr/visualizations/*.svg
          retention-days: 14
