name: Dependency Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/src/**'
      - 'frontend/src/**'
      - '.github/workflows/dependency-validation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/src/**'
      - 'frontend/src/**'
      - '.github/workflows/dependency-validation.yml'

jobs:
  validate-backend-dependencies:
    name: Validate Backend Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps
          
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
          
      - name: Check for circular dependencies
        run: |
          cd backend
          npm run dep:check-circular
          
      - name: Generate dependency visualization
        if: success() || failure()
        run: |
          cd backend
          npm run dep:graph
          npm run dep:modules
          npm run dep:archi
          
      - name: Upload dependency graphs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: backend-dependency-graphs
          path: |
            backend/dependency-graph.svg
            backend/module-dependencies.svg
            backend/architecture.svg
          
  validate-frontend-dependencies:
    name: Validate Frontend Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          
      - name: Install Graphviz
        run: sudo apt-get install -y graphviz
          
      - name: Check for circular dependencies
        run: |
          cd frontend
          npm run dep:check-circular
          
      - name: Generate dependency visualization
        if: success() || failure()
        run: |
          cd frontend
          npm run dep:graph
          npm run dep:components
          npm run dep:archi
          
      - name: Upload dependency graphs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dependency-graphs
          path: |
            frontend/dependency-graph.svg
            frontend/component-dependencies.svg
            frontend/architecture.svg